import {
  Problem,
  UniversityMatchResult,
  SolutionItem,
  UniversityAssignment,
  IndustryInterest,
  CollaborationItem,
  NotificationItem,
} from '../types';

export const INITIAL_PROBLEMS: Problem[] = [
  {
    problemId: 'CF-2026-001',
    title: 'Unsafe school toilets causing students to miss classes',
    description:
      'The government school in Namkum, Ranchi has severely damaged and unusable toilets. Students (especially girls) are frequently unable to attend classes because there are no functional sanitation facilities. The problem creates both a sanitation failure and a direct education access problem.',
    location: {
      address: 'Government Girls High School, Namkum',
      district: 'Ranchi',
      state: 'Jharkhand',
      latitude: 23.3441,
      longitude: 85.3096,
    },
    submittedAt: '2026-09-20T10:30:00Z',
    submitterId: 'CIT-901',
    submitterName: 'Ramesh Kumar',
    primaryDomain: 'Sanitation',
    subcategory: 'Toilets',
    secondaryDomains: ['Education'],
    severity: 'HIGH',
    urgency: 'HIGH',
    confidence: 0.91,
    status: 'University Assigned',
    stage: 'MATCH',
    aiClassification: {
      primaryDomain: 'Sanitation',
      subcategory: 'Toilets',
      secondaryDomains: ['Education'],
      severity: 'HIGH',
      urgency: 'HIGH',
      confidence: 0.91,
      reasoning: 'Explicit sanitation facility damage impacting student attendance',
      severityEvidence: ['unusable toilets', 'missing classes'],
      requiredExpertise: ['Sanitation Infrastructure', 'Water Supply Design'],
      requiredResources: ['Modular Toilets', 'Water Pipeline Infrastructure'],
      researchRequired: true,
      governmentActionPossible: true,
    },
  },
  {
    problemId: 'CF-2026-002',
    title: 'Toxic agricultural waste runoff contaminating local pond',
    description:
      'Pesticides and untreated chemical fertilizer runoff from nearby commercial crop fields are entering the community drinking water pond in Dhanbad. Over 300 households rely on this source for washing and cattle.',
    location: {
      address: 'Pond No. 3, Govindpur Village',
      district: 'Dhanbad',
      state: 'Jharkhand',
      latitude: 23.8,
      longitude: 86.43,
    },
    submittedAt: '2026-09-22T14:15:00Z',
    submitterId: 'CIT-902',
    submitterName: 'Anita Devi',
    primaryDomain: 'Environment',
    subcategory: 'Pollution',
    secondaryDomains: ['Water Resources', 'Healthcare'],
    severity: 'CRITICAL',
    urgency: 'CRITICAL',
    confidence: 0.94,
    status: 'Under Review',
    stage: 'VALIDATE',
    reviewRequired: true,
    reviewReason: 'Critical severity environmental contamination requiring government verification',
    aiClassification: {
      primaryDomain: 'Environment',
      subcategory: 'Pollution',
      secondaryDomains: ['Water Resources', 'Healthcare'],
      severity: 'CRITICAL',
      urgency: 'CRITICAL',
      confidence: 0.94,
      reasoning: 'Agricultural runoff threatening village water safety',
      severityEvidence: ['toxic chemical runoff', 'drinking pond contamination'],
      requiredExpertise: ['Environmental Chemistry', 'Water Quality Monitoring'],
      requiredResources: ['Water Quality Testing Kits', 'Bio-filtration Barriers'],
      researchRequired: true,
      governmentActionPossible: true,
    },
  },
  {
    problemId: 'CF-2026-003',
    title: 'Deep hazardous potholes on National Highway 33 bypass',
    description:
      'Multiple 2-foot deep potholes have opened up near the Kokar industrial junction. Three commuter accidents were reported in the last 48 hours.',
    location: {
      address: 'Kokar Industrial Area Bypass',
      district: 'Ranchi',
      state: 'Jharkhand',
      latitude: 23.37,
      longitude: 85.34,
    },
    submittedAt: '2026-09-24T08:45:00Z',
    submitterId: 'CIT-903',
    submitterName: 'Sanjay Verma',
    primaryDomain: 'Urban Infrastructure',
    subcategory: 'Roads',
    secondaryDomains: ['Public Administration'],
    severity: 'HIGH',
    urgency: 'CRITICAL',
    confidence: 0.88,
    status: 'Routed Government',
    stage: 'ROUTE',
    assignedDepartment: 'Public Works Department (PWD)',
    assignedOfficer: 'Er. R. K. Shrivastava',
    aiClassification: {
      primaryDomain: 'Urban Infrastructure',
      subcategory: 'Roads',
      secondaryDomains: ['Public Administration'],
      severity: 'HIGH',
      urgency: 'CRITICAL',
      confidence: 0.88,
      reasoning: 'Hazardous highway road surface damage causing vehicle accidents',
      severityEvidence: ['multiple deep craters', '3 accidents reported'],
      requiredExpertise: ['Civil Engineering', 'Asphalt Patching'],
      requiredResources: ['Bitumen Mixture', 'Heavy Road Roller'],
      researchRequired: false,
      governmentActionPossible: true,
    },
  },
  {
    problemId: 'CF-2026-004',
    title: 'Frequent solar microgrid voltage surges damaging household lamps',
    description:
      'In Silli village, the off-grid solar microgrid experiences un-regulated voltage spikes every evening, burning out LED bulbs and small agricultural motors.',
    location: {
      address: 'Silli Central Solar Facility',
      district: 'Ranchi',
      state: 'Jharkhand',
      latitude: 23.35,
      longitude: 85.85,
    },
    submittedAt: '2026-09-25T11:00:00Z',
    submitterId: 'CIT-904',
    submitterName: 'Manoj Mahto',
    primaryDomain: 'Energy',
    subcategory: 'Renewable Energy',
    secondaryDomains: ['Rural Livelihoods'],
    severity: 'MODERATE',
    urgency: 'MODERATE',
    confidence: 0.78,
    status: 'Under Review',
    stage: 'VALIDATE',
    reviewRequired: true,
    reviewReason: 'Confidence < 0.85 requires human review',
    aiClassification: {
      primaryDomain: 'Energy',
      subcategory: 'Renewable Energy',
      secondaryDomains: ['Rural Livelihoods'],
      severity: 'MODERATE',
      urgency: 'MODERATE',
      confidence: 0.78,
      reasoning: 'Microgrid power stabilization and voltage regulator issue',
      severityEvidence: ['voltage spikes', 'burned out appliances'],
      requiredExpertise: ['Electrical Engineering', 'Smart Inverter Design'],
      requiredResources: ['Voltage Stabilizer Module', 'Grid Telemetry Unit'],
      researchRequired: true,
      governmentActionPossible: true,
    },
  },
];

export const INITIAL_MATCHES: Record<string, UniversityMatchResult[]> = {
  'CF-2026-001': [
    {
      universityId: 'UNI-BIT-001',
      universityName: 'Birla Institute of Technology (BIT Mesra)',
      finalScore: 88.5,
      rank: 1,
      factorScores: {
        expertise: 0.95,
        faculty: 0.9,
        infrastructure: 0.85,
        pastProjects: 0.8,
        geography: 1.0,
        capacity: 0.8,
        industry: 0.75,
      },
      matchedExpertise: ['Sanitation Infrastructure', 'Water Supply Design', 'Environmental Engineering'],
      unmatchedExpertise: [],
      matchedFaculty: ['Dr. A. K. Singh (Environmental Dept)', 'Prof. S. Roy (Civil Dept)'],
      matchedInfrastructure: ['Fluid Mechanics Lab', 'Environmental Sanitation Bench'],
      relevantPastProjects: ['Modular Low-Cost School Toilets Study', 'Ranchi Rural Water Sanitation Project'],
      geographyReason: 'Same district (Ranchi, Jharkhand)',
      capacityReason: '4 free project slots out of 10 (AVAILABLE)',
      industryReason: 'Industry partner ties with CleanTech Innovations',
      explanation:
        'BIT Mesra scored top matching score due to strong faculty expertise in Sanitation Infrastructure, campus proximity in Ranchi, and prior school toilet research.',
    },
    {
      universityId: 'UNI-NIT-002',
      universityName: 'National Institute of Technology (NIT Jamshedpur)',
      finalScore: 76.2,
      rank: 2,
      factorScores: {
        expertise: 0.85,
        faculty: 0.8,
        infrastructure: 0.75,
        pastProjects: 0.6,
        geography: 0.6,
        capacity: 0.6,
        industry: 0.7,
      },
      matchedExpertise: ['Water Supply Design', 'Environmental Engineering'],
      unmatchedExpertise: ['Sanitation Infrastructure'],
      matchedFaculty: ['Dr. P. Roy'],
      matchedInfrastructure: ['Water Quality Testing Unit'],
      relevantPastProjects: ['Subarnarekha Basin Sanitation Study'],
      geographyReason: 'Same state (Jharkhand), different district (Jamshedpur)',
      capacityReason: '2 free project slots out of 8',
      industryReason: 'Tata Steel CSR Partnership',
      explanation: 'NIT Jamshedpur has high technical capability but lower geographic score.',
    },
  ],
};

export const INITIAL_ASSIGNMENTS: UniversityAssignment[] = [
  {
    assignmentId: 'ASN-BIT-8801',
    problemId: 'CF-2026-001',
    universityId: 'UNI-BIT-001',
    rank: 1,
    status: 'SENT',
    score: 88.5,
    scoreSnapshot: {
      expertise: 0.95,
      faculty: 0.9,
      infrastructure: 0.85,
      pastProjects: 0.8,
      geography: 1.0,
      capacity: 0.8,
      industry: 0.75,
    },
    explanation: 'Rank 1 university matching assignment sent to BIT Mesra SPOC.',
    sentAt: '2026-09-24T12:00:00Z',
    deadline: '2026-09-26T12:00:00Z',
  },
];

export const INITIAL_SOLUTIONS: SolutionItem[] = [
  {
    solutionId: 'SOL-SANIT-01',
    problemId: 'CF-2026-001',
    projectId: 'PRJ-BIT-901',
    universityId: 'UNI-BIT-001',
    universityName: 'BIT Mesra',
    title: 'Eco-Friendly Biogas Modular School Toilet Unit',
    domain: 'Sanitation',
    subcategory: 'Toilets',
    location: {
      state: 'Jharkhand',
      district: 'Ranchi',
    },
    developmentStage: 'PROTOTYPE',
    supportNeeded: ['Hardware', 'Testing', 'Funding'],
    partnerType: ['Industry', 'CSR', 'MSME'],
    visibility: 'PUBLIC',
    status: 'PUBLISHED',
    description:
      'Self-contained modular toilet structure with integrated anaerobic bio-digester converting school organic waste into biogas for canteen cooking while eliminating open sewage discharge.',
  },
  {
    solutionId: 'SOL-WATER-02',
    problemId: 'CF-2026-002',
    projectId: 'PRJ-IIT-402',
    universityId: 'UNI-IIT-ISM',
    universityName: 'IIT (ISM) Dhanbad',
    title: 'Nanocomposite Bio-Filtration Water Purification Unit',
    domain: 'Environment',
    subcategory: 'Pollution',
    location: {
      state: 'Jharkhand',
      district: 'Dhanbad',
    },
    developmentStage: 'PILOT',
    supportNeeded: ['Testing', 'Mentorship', 'Deployment Support'],
    partnerType: ['Industry', 'Startup'],
    visibility: 'PUBLIC',
    status: 'PUBLISHED',
    description:
      'Affordable gravity-fed water filter utilizing natural local clay and clay nanocomposite to absorb pesticide runoff and heavy agricultural metals.',
  },
];

export const INITIAL_INTERESTS: IndustryInterest[] = [
  {
    interestId: 'INT-CLEANTECH-01',
    solutionId: 'SOL-SANIT-01',
    partnerId: 'IND-CLEANTECH-99',
    partnerName: 'CleanTech Innovations Pvt Ltd',
    supportOffered: ['Hardware', 'Testing'],
    contribution: {
      hardware: ['4 modular FRP toilet shells', 'Bio-digester tanks'],
      valueInr: '₹2,50,000',
    },
    message:
      'We are eager to co-deploy our FRP modular shells with BIT Mesra design for Namkum school.',
    status: 'PENDING',
    createdAt: '2026-09-25T15:30:00Z',
  },
];

export const INITIAL_COLLABORATIONS: CollaborationItem[] = [
  {
    collaborationId: 'COL-TATA-77',
    solutionId: 'SOL-WATER-02',
    partnerId: 'CSR-TATA-TRUST',
    acceptedBy: 'UNI-IIT-ISM',
    supportDetails: {
      supportOffered: ['Deployment Support', 'Funding'],
      contribution: {
        grantAmount: '₹5,00,000',
        sitesCount: 3,
      },
    },
    status: 'ACTIVE',
    createdAt: '2026-09-23T09:00:00Z',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'NOTIF-01',
    title: 'University Match Found',
    message: 'BIT Mesra has been identified as Rank 1 match (Score 88.5/100) for Problem CF-2026-001.',
    timestamp: '10 mins ago',
    read: false,
    type: 'success',
    link: '/citizen/problems/CF-2026-001',
  },
  {
    id: 'NOTIF-02',
    title: 'Review Required',
    message: 'Problem CF-2026-002 requires human review due to CRITICAL severity classification.',
    timestamp: '1 hour ago',
    read: false,
    type: 'warning',
    link: '/government/review/CF-2026-002',
  },
  {
    id: 'NOTIF-03',
    title: 'Industry Partner Interest',
    message: 'CleanTech Innovations submitted an offer of Hardware support for Solution SOL-SANIT-01.',
    timestamp: '3 hours ago',
    read: true,
    type: 'info',
    link: '/university/assignments',
  },
];
